### ISSUE TITLE
MP does not seem to work

### ISSUE THREAD

**Issue by vanosten** [l0k1/eurofighter#6]
Hi

Other MP can see the airplane in e.g. the pilot list. However the pilot list is not available in the plane and other MP objects (e.g. the Vinson MP carrier) cannot be seen neither visually nor e.g. TACAN. I have no problems in other planes.

Window 10, next branch.

In the log:
Multiplayer mode active!
Nasal runtime error: No such member: loadMPList
  at /sim/bindings/menu/binding[194], line 1
Nasal runtime error: No such member: loadMPList
  at /sim/bindings/menu/binding[194], line 1
P

**Comment by l0k1** [comment]
Pilot List was intentionally overwritten so it would not work. In lieu of this no longer being an OPRF aircraft, I've reenabled it.

I was unable to duplicate your multiplayer problem, however - things were working fine on my end.

**Comment by l0k1** [comment]
Close was accidental, sorry.

**Comment by vanosten** [comment]
I works. 

(It would be nice to have the Typhoon back in OPRF - just have hiding in MP as an option like in the Viggen).
